// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using firello.Data;

#nullable disable

namespace firello.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("firello.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "POPULAR"
                        },
                        new
                        {
                            Id = 2,
                            Name = "WINTER"
                        },
                        new
                        {
                            Id = 3,
                            Name = "VARIOUS"
                        },
                        new
                        {
                            Id = 4,
                            Name = "EXOTIC"
                        },
                        new
                        {
                            Id = 5,
                            Name = "GREENS"
                        },
                        new
                        {
                            Id = 6,
                            Name = "CACTUSES"
                        });
                });

            modelBuilder.Entity("firello.Models.Expert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Expert");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "h3-team-img-1.png",
                            Name = "CRYSTAL BROOKS",
                            Profession = "Florist"
                        },
                        new
                        {
                            Id = 2,
                            Image = "h3-team-img-2.png",
                            Name = "SHIRLEY HARRIS",
                            Profession = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Image = "h3-team-img-3.png",
                            Name = "BEVERLY CLARK",
                            Profession = "Florist"
                        },
                        new
                        {
                            Id = 4,
                            Image = "h3-team-img-4.png",
                            Name = "AMANDA WATKINS",
                            Profession = "Florist"
                        });
                });

            modelBuilder.Entity("firello.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Desc1",
                            Name = "Product1",
                            Price = 259m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "desc2",
                            Name = "Product2",
                            Price = 259m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "desc3",
                            Name = "Product3",
                            Price = 259m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "desc4",
                            Name = "Product4",
                            Price = 259m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "desc5",
                            Name = "Product5",
                            Price = 259m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Description = "desc6",
                            Name = "Product6",
                            Price = 259m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "desc7",
                            Name = "Product7",
                            Price = 259m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "desc8",
                            Name = "Product8",
                            Price = 259m
                        });
                });

            modelBuilder.Entity("firello.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsMain = false,
                            Name = "shop-14-img.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsMain = false,
                            Name = "shop-13-img.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            IsMain = false,
                            Name = "shop-12-img.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            IsMain = false,
                            Name = "shop-11-img.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 5,
                            IsMain = false,
                            Name = "shop-10-img.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 6,
                            IsMain = false,
                            Name = "shop-9-img.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 7,
                            IsMain = false,
                            Name = "shop-8-img.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 8,
                            IsMain = false,
                            Name = "shop-7-img.jpg",
                            ProductId = 8
                        });
                });

            modelBuilder.Entity("firello.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "h3-slider-background.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Name = "h3-slider-background-2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Name = "h3-slider-background-3.jpg"
                        });
                });

            modelBuilder.Entity("firello.Models.SliderInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SliderInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Where flowers are our inspiration to create lasting memories. Whatever the occasion, our flowers will make it special cursus a sit amet mauris.",
                            Signature = "h2-sign-img.png",
                            Title = "<h1>Send<span>flowers</span>like</h1><h1>you mean it </h1>"
                        });
                });

            modelBuilder.Entity("firello.Models.SurpriseImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("SupriseImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SurpriseImage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SupriseImage = "h3-video-img.jpg"
                        });
                });

            modelBuilder.Entity("firello.Models.SurprisePanel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SurpriseText");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Where flowers are our inspiration to create lasting memories. Whatever the occasion...",
                            Title = "<h1>Suprise Your<span>Valentine!</span> Let us arrange a smile.</h1>"
                        });
                });

            modelBuilder.Entity("firello.Models.Product", b =>
                {
                    b.HasOne("firello.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("firello.Models.ProductImage", b =>
                {
                    b.HasOne("firello.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("firello.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("firello.Models.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
